### ISSUE TITLE
The Voyage Process - Getting off to a Solid Start!

### ISSUE THREAD

**Issue by jdmedlock** [chingu-voyages/v44-tier3-team-39#13]
**__Feature Description__**
Chingu has created a process for you to follow during the Voyage. This process helps you to get off on a solid start.

**__Major User Stories/tasks__**
- [x] Step 1: 🤝 Meet your team & schedule Kickoff meeting #5 
- [x] Step 2: 🧑‍🤝‍🧑 Conduct Kickoff meeting #6 
- [x] Step 3: 👍 Choose a project & create a Vision Statement #7 
- [x] Step 4: 📤 Define & prioritize MVP features #8 
- [x] Step 5: 📋 Create a Project Backlog #9 
- [x] Step 6: 📝 Create a Low-fidelity wireframe #14 
- [x] Step 7: ⚙️ Set Up a Team Workflow #10 

**__Additional Considerations__**
N/a

**Comment by Remontz** [comment]
Step 1/2:  KickOff : https://docs.google.com/document/d/13EpVfJ0kuVcoAigYSgEGd6YXhAyjte4R/edit?usp=sharing&ouid=105272198766389363660&rtpof=true&sd=true

Step 3/4: Choose Project | Vision Statement  
- [ X] https://docs.google.com/document/d/1Dv599A8-siVW0XZ8mRYb9Wnea8uDSJtQ/edit?usp=sharing&ouid=105272198766389363660&rtpof=true&sd=true 
- [X] https://docs.google.com/spreadsheets/d/1wPnYTAohgOzm4ME3Dp_gS7BqBBHhZBXd/edit#gid=1909728823

Step 5: BackLog |  https://docs.google.com/document/d/1lh28_R396zY-HFO9-UuodUpZnnauynuUIkMTDyIIfNc/edit?usp=sharing

Step 6: 

1.  https://drive.google.com/file/d/1Fr4zSta2EeO75_77LPLRnFz_te8wnms_/view?usp=sharing
2. https://www.figma.com/proto/DYMlaUNHO34aNuLG9gGt27/Milestone-App?type=design&node-id=1309-1824&scaling=min-zoom&page-id=1308%3A1267

Step 7: Trello & Github
